<template>
    <section class="d-flex align-items-start justify-content-center py-4">
        <div class="card p-4 rounded-2" style="max-width: 800px; width: 100%;">
            <div class="card-body">
                <h3 class="text-center mb-4">Terms and Conditions</h3>
                <div class="terms-content">
                    <small class="text-secondary">Last Updated on 16/02/2025</small>
                    <h5 class="fw-bold mb-3">1. Acceptance of Terms</h5>
                    <p class="mb-4">
                        By accessing and using ExamBhai, you agree to be bound by these Terms and Conditions.
                    </p>

                    <h5 class="fw-bold mb-3">2. User Accounts</h5>
                    <p class="mb-4">
                        Users must provide accurate and complete information when creating an account.
                        You are responsible for maintaining the confidentiality of your account credentials.
                    </p>

                    <h5 class="fw-bold mb-3">3. User Conduct</h5>
                    <p class="mb-4">
                        Users are expected to conduct themselves in a respectful and lawful manner while using the
                        platform. Prohibited behaviors include, but are not limited to:
                    </p>
                    <ul class="mb-4">
                        <li>Original or properly attributed</li>
                        <li>Free from offensive or inappropriate content</li>
                        <li>Compliant with our community guidelines</li>
                    </ul>

                    <h5 class="fw-bold mb-3">4. Privacy Policy</h5>
                    <p class="mb-4">
                        We value your privacy and are committed to protecting your personal information. Our Privacy
                        Policy outlines the types of data we collect, how we use it, and the measures we take to ensure
                        its security. We do not share your information with third parties without your consent, except
                        as required by law.
                    </p>

                    <h5 class="fw-bold mb-3">5. Termination</h5>
                    <p class="mb-4">
                        We reserve the right to terminate or suspend access to our service immediately,
                        without prior notice or liability, for any reason whatsoever.
                    </p>

                    <h5 class="fw-bold mb-3">6. Changes to Terms</h5>
                    <p class="mb-4">
                        We reserve the right to modify these terms at any time. We will notify users
                        of any changes by updating the date at the top of these terms.
                    </p>

                    <h5 class="fw-bold mb-3">7. Use of Platform</h5>
                    <p class="mb-4">
                        The platform is intended for educational purposes. Users shall not misuse the platform
                        or its content for any illegal or unauthorized purpose.
                    </p>

                    <h5 class="fw-bold mb-3">8. Intellectual Property</h5>
                    <p class="mb-4">
                        All content on ExamBhai, including quizzes, text, graphics, logos, and images,
                        is the property of ExamBhai or its content suppliers and protected by copyright laws.
                    </p>

                    <h5 class="fw-bold mb-3">9. Limitation of Liability</h5>
                    <p class="mb-4">
                        ExamBhai shall not be liable for any indirect, incidental, special, consequential, or
                        punitive damages, or any loss of profits or revenues.
                    </p>

                    <h5 class="fw-bold mb-3">10. Disclaimer of Warranty</h5>
                    <p class="mb-4">
                        The service is provided on an "AS IS" and "AS AVAILABLE" basis. ExamBhai makes no
                        warranties, express or implied, regarding the service.
                    </p>

                    <h5 class="fw-bold mb-3">11. Governing Law</h5>
                    <p class="mb-4">
                        These terms shall be governed by and construed in accordance with the laws of
                        India, without regard to its conflict of law provisions.
                    </p>

                    <h5 class="fw-bold mb-3">12. Contact Information</h5>
                    <p class="mb-4">
                        If you have any questions about these Terms and Conditions, please contact us at
                        <a href="mailto:contact@exambhai.com">contact@exambhai.com</a>.
                    </p>
                    <small style="font-size: 8px;">*This was generated by AI</small>
                </div>
            </div>
        </div>
    </section>
</template>
